### ISSUE TITLE
Do not use this!

### ISSUE THREAD

**Issue by Sanchezo** [bpedro/express-glitch-keepalive#1]
If you will use this package glitch will suspend your project!

**Comment by officiallyemma** [comment]
+1. Using this project instantly got my project suspended. I had a custom domain attached when the project got suspended which resulted in the domain being stuck in limbo. When you go to add your custom domain to a new project, it will return a 409 error, indicating that the domain is in use in another project (the suspended one)

However, I found a workaround:
1. Download your files from the suspended project and create a new one, reuploading the same files.
2. Add a new random custom domain (asdkjhsdfkjhsdf.com or something like that)
3. open dev tools and monitor network requests
4. remove the custom domain. 
You should see a DELETE request sent to `https://api.glitch.com/v1/projects/**NEW PROJECT ID**/domains`. Right-click this request and select copy > copy as fetch. save this js somewhere, we'll need it for later
5. next you need to get the UUID of your *suspended* project. The best way I found to get this was to monitor the network traffic while archiving the suspended project. You should see a DELETE request to `https://api.glitch.com/v1/projects/by/id?id=**your suspended project uuid**`, save this id
6. Next, you need to open dev tools console and paste in the copied JS fetch and edit it a little.

```Javascript
fetch("https://api.glitch.com/v1/projects/**PUT YOUR SUSPENDED PROJECT ID HERE**/domains", { // insert suspended project's uuid here
  "headers": {
    "accept": "application/json",
    "accept-language": "en-US,en;q=0.9",
    "authorization": "REDACTED - THIS WILL CONTAIN YOUR USER TOKEN, don't share it",
    "content-type": "application/json",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-site"
  },
  "referrer": "https://glitch.com/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"domain\":\"**PUT YOUR CUSTOM DOMAIN HERE .com**\"}", // insert the custom domain here
  "method": "DELETE",
  "mode": "cors",
  "credentials": "include"
});

```

7. press enter and check the network tab to see if your request succeeded
8. now your custom domain is detached from the suspended project and ready to be attached to your new project

**Comment by tiagorangel2011** [comment]
Or just ask the staff to unban it. They will remove the package and unban your project.

> +1. Using this project instantly got my project suspended. I had a custom domain attached when the project got suspended which resulted in the domain being stuck in limbo. When you go to add your custom domain to a new project, it will return a 409 error, indicating that the domain is in use in another project (the suspended one)
> 
> However, I found a workaround:
> 
>     1. Download your files from the suspended project and create a new one, reuploading the same files.
> 
>     2. Add a new random custom domain (asdkjhsdfkjhsdf.com or something like that)
> 
>     3. open dev tools and monitor network requests
> 
>     4. remove the custom domain.
>        You should see a DELETE request sent to `https://api.glitch.com/v1/projects/**NEW PROJECT ID**/domains`. Right-click this request and select copy > copy as fetch. save this js somewhere, we'll need it for later
> 
>     5. next you need to get the UUID of your _suspended_ project. The best way I found to get this was to monitor the network traffic while archiving the suspended project. You should see a DELETE request to `https://api.glitch.com/v1/projects/by/id?id=**your suspended project uuid**`, save this id
> 
>     6. Next, you need to open dev tools console and paste in the copied JS fetch and edit it a little.
> 
> 
> ```js
> fetch("https://api.glitch.com/v1/projects/**PUT YOUR SUSPENDED PROJECT ID HERE**/domains", { // insert suspended project's uuid here
>   "headers": {
>     "accept": "application/json",
>     "accept-language": "en-US,en;q=0.9",
>     "authorization": "REDACTED - THIS WILL CONTAIN YOUR USER TOKEN, don't share it",
>     "content-type": "application/json",
>     "sec-fetch-dest": "empty",
>     "sec-fetch-mode": "cors",
>     "sec-fetch-site": "same-site"
>   },
>   "referrer": "https://glitch.com/",
>   "referrerPolicy": "strict-origin-when-cross-origin",
>   "body": "{\"domain\":\"**PUT YOUR CUSTOM DOMAIN HERE .com**\"}", // insert the custom domain here
>   "method": "DELETE",
>   "mode": "cors",
>   "credentials": "include"
> });
> ```
> 
>     7. press enter and check the network tab to see if your request succeeded
> 
>     8. now your custom domain is detached from the suspended project and ready to be attached to your new project
