### ISSUE TITLE
This project results in the instant suspension of your glitch project

### ISSUE THREAD

**Issue by officiallyemma** [bpedro/express-glitch-keepalive#2]
upon adding this repo to the packages.json file in glitch, your project will be instantly suspended. I think that there should be a disclaimer in the README.md file somewhere. If you want to keep this project alive, perhaps a workaround would be to include copy-pastable code instead of using this flagged repo. Also, if the project has a custom domain attached when it is suspended, the domain will be stuck in limbo, unable to be added to a new project. However, I found a workaround for this bug and described it in #1.

**Comment by Desintegrator** [comment]
+1

**Comment by tiagorangel2011** [comment]
Yes, you can just ask the staff to unban it but it's a hassle, takes time and will potentially leak your envs (there is no public information about how private envs are).
